- name: Pakiety
  pip:
    name: 
    - docker
    - docker-compose
- name: Git 
  git:
    repo: "{{ git_repository }}"
    dest: "{{ deployment_path }}"
    version: "{{ git_branch }}"
- name: `docker-compose up`
  docker_compose:
    project_src: "{{ deployment_path }}"
    build: yes
    debug: yes
